/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2e52cc78d88157dc216c347c1c6d38a9)
interface __BaseEnv_Env {
	LIBRARY: DurableObjectNamespace<import("./src/index").ReaderLibrary>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ReaderLibrary";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
