// Mozilla User Preferences (aka about:config)
// Put this user.js in firefox profile folder

user_pref("browser.download.autohideButton", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.search.widget.inNavBar", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.urlbar.trimURLs", false);
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.pocket.enabled", false);
user_pref("font.language.group", "zh-CN");
user_pref("font.name-list.cursive.ar", "LXGW WenKai");
user_pref("font.name-list.cursive.el", "LXGW WenKai");
user_pref("font.name-list.cursive.he", "LXGW WenKai");
user_pref("font.name-list.cursive.ko", "LXGW WenKai");
user_pref("font.name-list.cursive.th", "LXGW WenKai");
user_pref("font.name-list.cursive.x-cyrillic", "LXGW WenKai");
user_pref("font.name-list.cursive.x-ethi", "LXGW WenKai");
user_pref("font.name-list.cursive.x-math", "LXGW WenKai");
user_pref("font.name-list.cursive.x-unicode", "LXGW WenKai");
user_pref("font.name-list.cursive.x-western", "LXGW WenKai");
user_pref("font.name-list.cursive.zh-CN", "LXGW WenKai");
user_pref("font.name-list.cursive.zh-HK", "LXGW WenKai");
user_pref("font.name-list.cursive.zh-TW", "LXGW WenKai");
user_pref("font.name-list.monospace.ar", "Maple Mono SC NF");
user_pref("font.name-list.monospace.el", "Maple Mono SC NF");
user_pref("font.name-list.monospace.he", "Maple Mono SC NF");
user_pref("font.name-list.monospace.ja", "Maple Mono SC NF");
user_pref("font.name-list.monospace.ko", "Maple Mono SC NF");
user_pref("font.name-list.monospace.th", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-armn", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-beng", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-cans", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-cyrillic", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-devanagari", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-ethi", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-geor", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-gujr", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-guru", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-khmr", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-knda", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-math", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-mlym", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-orya", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-sinh", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-tamil", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-telu", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-tibt", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-unicode", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-western", "Maple Mono SC NF");
user_pref("font.name-list.monospace.zh-CN", "Maple Mono SC NF");
user_pref("font.name-list.monospace.zh-HK", "Maple Mono SC NF");
user_pref("font.name-list.monospace.zh-TW", "Maple Mono SC NF");
user_pref("font.name-list.sans-serif.ar", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.el", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.he", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.ja", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.ko", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.th", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-armn", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-beng", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-cans", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-cyrillic", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-devanagari", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-ethi", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-geor", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-gujr", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-guru", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-khmr", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-knda", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-math", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-mlym", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-orya", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-sinh", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-tamil", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-telu", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-tibt", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-unicode", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.x-western", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.zh-CN", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.zh-HK", "Dream Han Sans CN");
user_pref("font.name-list.sans-serif.zh-TW", "Dream Han Sans CN");
user_pref("font.name-list.serif.ar", "Dream Han Serif CN");
user_pref("font.name-list.serif.el", "Dream Han Serif CN");
user_pref("font.name-list.serif.he", "Dream Han Serif CN");
user_pref("font.name-list.serif.ja", "Dream Han Serif CN");
user_pref("font.name-list.serif.ko", "Dream Han Serif CN");
user_pref("font.name-list.serif.th", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-armn", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-beng", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-cans", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-cyrillic", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-devanagari", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-ethi", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-geor", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-gujr", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-guru", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-khmr", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-knda", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-math", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-mlym", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-orya", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-sinh", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-tamil", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-telu", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-tibt", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-unicode", "Dream Han Serif CN");
user_pref("font.name-list.serif.x-western", "Dream Han Serif CN");
user_pref("font.name-list.serif.zh-CN", "Dream Han Serif CN");
user_pref("font.name-list.serif.zh-HK", "Dream Han Serif CN");
user_pref("font.name-list.serif.zh-TW", "Dream Han Serif CN");
