// Mozilla User Preferences (aka about:config)
// Put this user.js in firefox profile folder

user_pref("browser.download.autohideButton", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.search.widget.inNavBar", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.urlbar.trimURLs", false);
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.pocket.enabled", false);
user_pref("font.language.group", "zh-CN");
user_pref("font.name-list.cursive.ar", "LXGW WenKai");
user_pref("font.name-list.cursive.el", "LXGW WenKai");
user_pref("font.name-list.cursive.he", "LXGW WenKai");
user_pref("font.name-list.cursive.ko", "LXGW WenKai");
user_pref("font.name-list.cursive.th", "LXGW WenKai");
user_pref("font.name-list.cursive.x-cyrillic", "LXGW WenKai");
user_pref("font.name-list.cursive.x-ethi", "LXGW WenKai");
user_pref("font.name-list.cursive.x-math", "LXGW WenKai");
user_pref("font.name-list.cursive.x-unicode", "LXGW WenKai");
user_pref("font.name-list.cursive.x-western", "LXGW WenKai");
user_pref("font.name-list.cursive.zh-CN", "LXGW WenKai");
user_pref("font.name-list.cursive.zh-HK", "LXGW WenKai");
user_pref("font.name-list.cursive.zh-TW", "LXGW WenKai");
user_pref("font.name-list.monospace.ar", "Maple Mono SC NF");
user_pref("font.name-list.monospace.el", "Maple Mono SC NF");
user_pref("font.name-list.monospace.he", "Maple Mono SC NF");
user_pref("font.name-list.monospace.ja", "Maple Mono SC NF");
user_pref("font.name-list.monospace.ko", "Maple Mono SC NF");
user_pref("font.name-list.monospace.th", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-armn", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-beng", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-cans", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-cyrillic", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-devanagari", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-ethi", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-geor", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-gujr", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-guru", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-khmr", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-knda", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-math", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-mlym", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-orya", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-sinh", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-tamil", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-telu", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-tibt", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-unicode", "Maple Mono SC NF");
user_pref("font.name-list.monospace.x-western", "Maple Mono SC NF");
user_pref("font.name-list.monospace.zh-CN", "Maple Mono SC NF");
user_pref("font.name-list.monospace.zh-HK", "Maple Mono SC NF");
user_pref("font.name-list.monospace.zh-TW", "Maple Mono SC NF");
user_pref("font.name-list.sans-serif.ar", "Source Sans 3");
user_pref("font.name-list.sans-serif.el", "Source Sans 3");
user_pref("font.name-list.sans-serif.he", "Source Sans 3");
user_pref("font.name-list.sans-serif.ja", "Microsoft YaHei, PingFang SC, Source Han Sans SC");
user_pref("font.name-list.sans-serif.ko", "Microsoft YaHei, PingFang SC, Source Han Sans SC");
user_pref("font.name-list.sans-serif.th", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-armn", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-beng", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-cans", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-cyrillic", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-devanagari", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-ethi", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-geor", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-gujr", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-guru", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-khmr", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-knda", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-math", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-mlym", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-orya", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-sinh", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-tamil", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-telu", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-tibt", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-unicode", "Source Sans 3");
user_pref("font.name-list.sans-serif.x-western", "Source Sans 3");
user_pref("font.name-list.sans-serif.zh-CN", "Microsoft YaHei, PingFang SC, Source Han Sans SC");
user_pref("font.name-list.sans-serif.zh-HK", "Microsoft YaHei, PingFang SC, Source Han Sans SC");
user_pref("font.name-list.sans-serif.zh-TW", "Microsoft YaHei, PingFang SC, Source Han Sans SC");
user_pref("font.name-list.serif.ar", "Source Serif 4");
user_pref("font.name-list.serif.el", "Source Serif 4");
user_pref("font.name-list.serif.he", "Source Serif 4");
user_pref("font.name-list.serif.ja", "Source Han Serif SC");
user_pref("font.name-list.serif.ko", "Source Han Serif SC");
user_pref("font.name-list.serif.th", "Source Serif 4");
user_pref("font.name-list.serif.x-armn", "Source Serif 4");
user_pref("font.name-list.serif.x-beng", "Source Serif 4");
user_pref("font.name-list.serif.x-cans", "Source Serif 4");
user_pref("font.name-list.serif.x-cyrillic", "Source Serif 4");
user_pref("font.name-list.serif.x-devanagari", "Source Serif 4");
user_pref("font.name-list.serif.x-ethi", "Source Serif 4");
user_pref("font.name-list.serif.x-geor", "Source Serif 4");
user_pref("font.name-list.serif.x-gujr", "Source Serif 4");
user_pref("font.name-list.serif.x-guru", "Source Serif 4");
user_pref("font.name-list.serif.x-khmr", "Source Serif 4");
user_pref("font.name-list.serif.x-knda", "Source Serif 4");
user_pref("font.name-list.serif.x-math", "Source Serif 4");
user_pref("font.name-list.serif.x-mlym", "Source Serif 4");
user_pref("font.name-list.serif.x-orya", "Source Serif 4");
user_pref("font.name-list.serif.x-sinh", "Source Serif 4");
user_pref("font.name-list.serif.x-tamil", "Source Serif 4");
user_pref("font.name-list.serif.x-telu", "Source Serif 4");
user_pref("font.name-list.serif.x-tibt", "Source Serif 4");
user_pref("font.name-list.serif.x-unicode", "Source Serif 4");
user_pref("font.name-list.serif.x-western", "Source Serif 4");
user_pref("font.name-list.serif.zh-CN", "Source Han Serif SC");
user_pref("font.name-list.serif.zh-HK", "Source Han Serif SC");
user_pref("font.name-list.serif.zh-TW", "Source Han Serif SC");
