/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7b57daead4dd834a886c0cc36b55da8c)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
